// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using HelloWorld;

namespace HelloWorld
{
	using csharp_station.tutorial;
	class Hello3
	{

		public static void Main() 
		{
			// Write to console
			myExample1.myPrint1(); 
			myExample1.myPrint2(); 
		}
		public static string Numbers(int[] ints)
		{
			for (int i = 0; i < ints.Length; i++)

			{
				Console.WriteLine("{0}", ints[i]); 
			}
			return "Function Complete";
		}
	}

}



