// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace OOPractice
{
	public class Item
	{
		public int ID { get; set;}
		public string Name { get; set;}
	}

	public class Shovels : Item
	{
		public string SerialNumber { get; set;}
	}

	public class Books : Item
	{
		public string ISBN { get; set;}
	}


	public class Comics : Books
	{
		string Publisher { get; set;}
		bool Colored { get; set;}

	}

	public class Biographies : Books
	{
		string Description {get;set;}
		
	}

}

